# Generated by Django 5.2.17 on 2026-09-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate_alter_experience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='thumbnail',
            field=models.CharField(max_length=255),
        ),
    ]
