# Generated by Django 5.2.17 on 2026-09-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_certificate_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
